from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from typing import Dict, List, Any
from datetime import datetime
import json
from config import Config

class ReportGenerator:
    """Generate PDF reports for cybersecurity health assessments"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.darkblue
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            textColor=colors.darkred
        ))
        
        self.styles.add(ParagraphStyle(
            name='SubHeader',
            parent=self.styles['Heading3'],
            fontSize=14,
            spaceAfter=8,
            textColor=colors.darkgreen
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBodyText',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=6
        ))
    
    def generate_health_report(self, health_data: Dict[str, Any], output_path: str = None) -> str:
        """Generate a comprehensive health report PDF"""
        
        if not output_path:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = f"cyberhealth_report_{timestamp}.pdf"
        
        doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=72, leftMargin=72, 
                              topMargin=72, bottomMargin=18)
        
        story = []
        
        # Title Page
        story.extend(self._create_title_page(health_data))
        story.append(PageBreak())
        
        # Executive Summary
        story.extend(self._create_executive_summary(health_data))
        story.append(PageBreak())
        
        # Detailed Results
        story.extend(self._create_detailed_results(health_data))
        story.append(PageBreak())
        
        # Recommendations
        story.extend(self._create_recommendations(health_data))
        story.append(PageBreak())
        
        # Appendices
        story.extend(self._create_appendices(health_data))
        
        doc.build(story)
        return output_path
    
    def _create_title_page(self, health_data: Dict[str, Any]) -> List:
        """Create the title page"""
        elements = []
        
        # Title
        title = Paragraph("🔐 Cybersecurity Health Report", self.styles['CustomTitle'])
        elements.append(title)
        elements.append(Spacer(1, 30))
        
        # Company Info
        company_info = f"""
        <b>Company:</b> {Config.REPORT_CONFIG['company_name']}<br/>
        <b>Report Date:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}<br/>
        <b>Generated By:</b> CyberHealth Assistant v1.0
        """
        elements.append(Paragraph(company_info, self.styles['CustomBodyText']))
        elements.append(Spacer(1, 40))
        
        # Overall Status
        overall_status = health_data.get('overall_status', 'UNKNOWN')
        status_color = {
            'HEALTHY': colors.green,
            'WARNING': colors.orange,
            'CRITICAL': colors.red
        }.get(overall_status, colors.grey)
        
        status_text = f"""
        <b>Overall Health Status:</b> <font color="{status_color}">{overall_status}</font><br/>
        <b>Assessment Period:</b> Last 24 hours<br/>
        <b>Tools Analyzed:</b> {len(health_data.get('tool_results', {}))} cybersecurity tools
        """
        elements.append(Paragraph(status_text, self.styles['CustomBodyText']))
        
        return elements
    
    def _create_executive_summary(self, health_data: Dict[str, Any]) -> List:
        """Create executive summary section"""
        elements = []
        
        # Section Header
        elements.append(Paragraph("Executive Summary", self.styles['SectionHeader']))
        elements.append(Spacer(1, 12))
        
        # Summary Text
        overall_status = health_data.get('overall_status', 'UNKNOWN')
        tool_results = health_data.get('tool_results', {})
        
        summary_text = f"""
        This cybersecurity health assessment provides a comprehensive overview of the security posture 
        across all monitored systems and tools. The analysis covers {len(tool_results)} critical 
        cybersecurity tools including SIEM, EDR, firewalls, and vulnerability management systems.
        
        <b>Key Findings:</b>
        • Overall Status: {overall_status}<br/>
        • Tools Analyzed: {len(tool_results)}<br/>
        • Critical Issues: {self._count_critical_issues(tool_results)}<br/>
        • Warning Issues: {self._count_warning_issues(tool_results)}<br/>
        • Healthy Systems: {self._count_healthy_systems(tool_results)}
        """
        
        elements.append(Paragraph(summary_text, self.styles['CustomBodyText']))
        elements.append(Spacer(1, 20))
        
        # Status Summary Table
        elements.extend(self._create_status_summary_table(tool_results))
        
        return elements
    
    def _create_detailed_results(self, health_data: Dict[str, Any]) -> List:
        """Create detailed results section"""
        elements = []
        
        elements.append(Paragraph("Detailed Assessment Results", self.styles['SectionHeader']))
        elements.append(Spacer(1, 12))
        
        tool_results = health_data.get('tool_results', {})
        
        for tool_name, results in tool_results.items():
            # Tool Header
            elements.append(Paragraph(f"Tool: {tool_name}", self.styles['SubHeader']))
            elements.append(Spacer(1, 8))
            
            # Tool Status
            status = results.get('overall_status', 'UNKNOWN')
            status_color = {
                'HEALTHY': colors.green,
                'WARNING': colors.orange,
                'CRITICAL': colors.red
            }.get(status, colors.grey)
            
            status_text = f"""
            <b>Status:</b> <font color="{status_color}">{status}</font><br/>
            <b>Summary:</b> {results.get('summary', 'No summary available')}<br/>
            <b>Timestamp:</b> {results.get('timestamp', 'Unknown')}
            """
            elements.append(Paragraph(status_text, self.styles['CustomBodyText']))
            elements.append(Spacer(1, 12))
            
            # Detailed Checks
            checks = results.get('checks', {})
            if checks:
                elements.append(Paragraph("Detailed Checks:", self.styles['CustomBodyText']))
                elements.append(Spacer(1, 6))
                
                check_data = []
                for check_name, check_result in checks.items():
                    check_status = check_result.get('status', 'UNKNOWN')
                    check_details = check_result.get('details', 'No details available')
                    if isinstance(check_details, dict):
                        check_details = json.dumps(check_details, indent=2)[:200] + "..."
                    
                    check_data.append([
                        check_name.replace('_', ' ').title(),
                        check_status,
                        str(check_details)[:100] + "..." if len(str(check_details)) > 100 else str(check_details)
                    ])
                
                if check_data:
                    table = Table([['Check Type', 'Status', 'Details']] + check_data)
                    table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 10),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                        ('GRID', (0, 0), (-1, -1), 1, colors.black)
                    ]))
                    elements.append(table)
                    elements.append(Spacer(1, 20))
        
        return elements
    
    def _create_recommendations(self, health_data: Dict[str, Any]) -> List:
        """Create recommendations section"""
        elements = []
        
        elements.append(Paragraph("Recommendations", self.styles['SectionHeader']))
        elements.append(Spacer(1, 12))
        
        # AI-generated recommendations
        ai_recommendations = health_data.get('ai_recommendations', [])
        if ai_recommendations:
            elements.append(Paragraph("AI-Generated Recommendations:", self.styles['SubHeader']))
            elements.append(Spacer(1, 8))
            
            for i, rec in enumerate(ai_recommendations, 1):
                rec_text = f"{i}. {rec}"
                elements.append(Paragraph(rec_text, self.styles['CustomBodyText']))
                elements.append(Spacer(1, 6))
        
        # Standard recommendations
        elements.append(Spacer(1, 12))
        elements.append(Paragraph("Standard Security Recommendations:", self.styles['SubHeader']))
        elements.append(Spacer(1, 8))
        
        standard_recs = [
            "Immediately address any critical security issues identified",
            "Review and update security policies and procedures",
            "Implement additional monitoring for detected threat patterns",
            "Schedule regular security assessments and penetration testing",
            "Ensure all security tools are properly configured and updated",
            "Provide security awareness training to all staff members",
            "Establish incident response procedures and test them regularly",
            "Maintain regular backups and test recovery procedures"
        ]
        
        for i, rec in enumerate(standard_recs, 1):
            rec_text = f"{i}. {rec}"
            elements.append(Paragraph(rec_text, self.styles['CustomBodyText']))
            elements.append(Spacer(1, 6))
        
        return elements
    
    def _create_appendices(self, health_data: Dict[str, Any]) -> List:
        """Create appendices section"""
        elements = []
        
        elements.append(Paragraph("Appendices", self.styles['SectionHeader']))
        elements.append(Spacer(1, 12))
        
        # Raw Data Appendix
        elements.append(Paragraph("Appendix A: Raw Assessment Data", self.styles['SubHeader']))
        elements.append(Spacer(1, 8))
        
        raw_data_text = f"""
        This appendix contains the raw data collected during the health assessment.
        The data is provided in JSON format for technical review and analysis.
        
        Assessment Timestamp: {health_data.get('timestamp', 'Unknown')}
        Total Tools Analyzed: {len(health_data.get('tool_results', {}))}
        Overall Status: {health_data.get('overall_status', 'Unknown')}
        """
        
        elements.append(Paragraph(raw_data_text, self.styles['CustomBodyText']))
        elements.append(Spacer(1, 12))
        
        # Raw JSON data (truncated for readability)
        raw_json = json.dumps(health_data, indent=2)
        if len(raw_json) > 2000:
            raw_json = raw_json[:2000] + "\n... (truncated for readability)"
        
        elements.append(Paragraph(f"<pre>{raw_json}</pre>", self.styles['CustomBodyText']))
        
        return elements
    
    def _create_status_summary_table(self, tool_results: Dict[str, Any]) -> List:
        """Create status summary table"""
        elements = []
        
        table_data = [['Tool Name', 'Status', 'Issues']]
        
        for tool_name, results in tool_results.items():
            status = results.get('overall_status', 'UNKNOWN')
            issues = self._count_issues_by_severity(results)
            table_data.append([tool_name, status, issues])
        
        table = Table(table_data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(table)
        return elements
    
    def _count_critical_issues(self, tool_results: Dict[str, Any]) -> int:
        """Count critical issues across all tools"""
        count = 0
        for results in tool_results.values():
            if results.get('overall_status') == 'CRITICAL':
                count += 1
        return count
    
    def _count_warning_issues(self, tool_results: Dict[str, Any]) -> int:
        """Count warning issues across all tools"""
        count = 0
        for results in tool_results.values():
            if results.get('overall_status') == 'WARNING':
                count += 1
        return count
    
    def _count_healthy_systems(self, tool_results: Dict[str, Any]) -> int:
        """Count healthy systems across all tools"""
        count = 0
        for results in tool_results.values():
            if results.get('overall_status') == 'HEALTHY':
                count += 1
        return count
    
    def _count_issues_by_severity(self, results: Dict[str, Any]) -> str:
        """Count issues by severity for a tool"""
        checks = results.get('checks', {})
        critical = sum(1 for check in checks.values() if check.get('status') == 'CRITICAL')
        warning = sum(1 for check in checks.values() if check.get('status') == 'WARNING')
        
        if critical > 0:
            return f"{critical} critical, {warning} warning"
        elif warning > 0:
            return f"{warning} warning"
        else:
            return "None"